### ISSUE TITLE
stops outputting mqtt and doesnt reconnect if mqtt broker is off network for more than a few minutes

### ISSUE THREAD

**Issue by gazzaman2k** [njfaria/bmvlog#1]
i use this with solpiplog and homeassistant, if i reboot my router or reboot homeassistant and it takes like 5minutes for it to reboot or reload all the integrations the bmv logger fails to reconnect back to the mqtt and just lies dormant, it shows it working in the app on the pi but homeassitant its not logged back into the broker, whilst solpiplog is still connected and publishing its data.

possible to run some sort of reconnect after 5minutes code or somthing until it connects back to broker?

thanks and thankyou for the great work

**Comment by njfaria** [comment]
i need to implement the reconnection code from solpiplog in the bmvlog ,
pylonlog and the other ones.
On todo list

gazzaman2k <notifications@github.com> escreveu no dia domingo, 3/01/2021
à(s) 12:34:

**Comment by gazzaman2k** [comment]
great thankyou for the quick response and great program :)

**Comment by drschrick12** [comment]
Hi, is the future now implemented in BMVlog ?
Sorry for asking but I need this future.

Thanks a lot.

**Comment by njfaria** [comment]
fixed in new release 1.1.0
